import { useState, useEffect, useCallback } from 'react'
import Sidebar from './components/Sidebar'
import StatsCards from './components/StatsCards'
import AlertsTable from './components/AlertsTable'
import EventsTable from './components/EventsTable'
import Charts from './components/Charts'
import LogUpload from './components/LogUpload'
import './styles/App.css'
import './styles/StatsCards.css'
import './styles/DataTable.css'
import './styles/components.css'

function App() {
  const [page, setPage] = useState('dashboard')
  const [alerts, setAlerts] = useState([])
  const [events, setEvents] = useState([])
  const [loading, setLoading] = useState(true)

  const fetchData = useCallback(async () => {
    try {
      const [alertsRes, eventsRes] = await Promise.all([
        fetch('/api/alerts'),
        fetch('/api/events'),
      ])
      if (alertsRes.ok) setAlerts(await alertsRes.json())
      if (eventsRes.ok) setEvents(await eventsRes.json())
    } catch (err) {
      console.error('Failed to fetch data:', err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchData()
    const interval = setInterval(fetchData, 10000)
    return () => clearInterval(interval)
  }, [fetchData])

  return (
    <div className="app">
      <Sidebar activePage={page} onNavigate={setPage} />
      <main className="main-content">
        {page === 'dashboard' && (
          <>
            <div className="page-header">
              <h1>Dashboard</h1>
              <p>Real-time threat intelligence overview</p>
            </div>
            <StatsCards alerts={alerts} events={events} />
            <Charts alerts={alerts} events={events} />
            <AlertsTable alerts={alerts.slice(0, 5)} compact onRefresh={fetchData} />
          </>
        )}
        {page === 'alerts' && (
          <>
            <div className="page-header">
              <h1>Alerts</h1>
              <p>Security alerts generated by detection rules</p>
            </div>
            <AlertsTable alerts={alerts} onRefresh={fetchData} />
          </>
        )}
        {page === 'events' && (
          <>
            <div className="page-header">
              <h1>Events</h1>
              <p>Parsed log events from ingested files</p>
            </div>
            <EventsTable events={events} />
          </>
        )}
        {page === 'upload' && (
          <>
            <div className="page-header">
              <h1>Upload Logs</h1>
              <p>Upload log files for analysis and threat detection</p>
            </div>
            <LogUpload onUploadSuccess={fetchData} />
          </>
        )}
      </main>
    </div>
  )
}

export default App
